server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices?useSSL=false&serverTimezone=UTC
    username: root
    password: Rahul@1502
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    com.zaxxer.hikari: DEBUG
    org.hibernate: DEBUG
